config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
    devise_for :users
    as :user do
        get 'signin' => 'devise/sessions#new'
        delete 'signout' => 'devise/sessions#destroy'
        get 'signup' => 'devise/registrations#new'
    end

  resources :questions do
    member do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end
  end    
  resources :answers do
    member do
      post 'vote', to: 'votes#create'
      delete 'unvote', to: 'votes#destroy'
    end
  end 

  get 'users/:username',  to:'users#show', as: 'user'

  
    root 'pages#home'
    get 'about' => 'pages#about' 
    get 'contact' => 'pages#contact'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter

    def authorized?(action, subject = nil)
        user && user.admin?
    end
    
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user 
  belongs_to :question

  validates :user, presence: true
  validates :question, presence: true
  validates :text, presence: true

  acts_as_votable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers


  validates :user, presence: true
  validates :content, presence: true

  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise  :database_authenticatable, :registerable,
            :rememberable, :trackable, :validatable
    has_many :questions
    has_many :answers

    validates :username, presence: true, uniqueness: true

    acts_as_voter
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  # GET /answers
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  def show
    @answer = Answer.find(params[:id])
  end

  # GET /answers/new
  def new
    @question = Question.find($the_question.id)
    @answer = current_user.answers.new
  end

  # GET /answers/1/edit
  def edit
    @answer = current_user.answers.find(params[:id])
  end

  # POST /answers

  def create
    question = Question.find($the_question.id)
    @answer = question.answers.new(answer_params)
    @answer.user_id=current_user.id
      if @answer.save
        redirect_to question, notice: 'Answer was successfully created.' 
      else
        @question = Question.find(question.id)
        render :new 
      end
  end

  # PATCH/PUT /answers/1
 
  def update
    @answer = current_user.answers.find(params[:id]) 
      if @answer.update(answer_params)
        redirect_to @answer, notice: 'Answer was successfully updated.' 
      else
        render :edit
      end
  end

  # DELETE /answers/1
  def destroy
    @answer = current_user.answers.find(params[:id])
    current_question = @answer.question
    @answer.destroy
    redirect_to current_question, notice: 'Answer was successfully destroyed.'
      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:text)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protect_from_forgery with: :exception

    def access_denied(exception)
        redirect_to root_path, alert: exception.message
    end
    

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    def create
        question = Question.find(params[:id])
        question.liked_by current_user
        redirect_to question_path, notice: 'You successfully liked this question'
    end

    def destroy
        question = Question.find(params[:id])
        question.unliked_by current_user
        redirect_to question_path, notice: 'You successfully unliked this question'
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  # GET /questions
 
  def index
    @questions = Question.all
  end

  # GET /questions/1
  def show
     @question = Question.find(params[:id])
   
     $the_question = Question.find(params[:id])
  end

  # GET /questions/new
  def new
    @question = current_user.questions.new
  end

  # GET /questions/1/edit
  def edit
    @question = current_user.questions.find(params[:id])
  end

  # POST /questions
  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /questions/1
  def update
    @question = current_user.questions.find(params[:id])
    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render :edit 
    end
  end

  # DELETE /questions/1
  def destroy
    @question = current_user.questions.find(params[:id])
    @question.destroy
    redirect_to questions_url, notice: 'Question was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(username: params[:username])
    @liked_questions = @user.get_up_voted Question
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
    before_action :authenticate_user!
    def create
        answer = Answer.find(params[:id])
        answer.liked_by current_user
        redirect_to answer.question, notice: 'You successfully voted for this answer'
    end

    def destroy
        answer = Answer.find(params[:id])
        answer.unliked_by current_user
        redirect_to answer.question, notice: 'You successfully unvoted for this answer'
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_area :text, id: :answer_text, class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary'%>
  </div>
<% end %>



  

app/views/answers/edit.html.erb
<div class="card w-75 mx-auto my-3">
    <div class="card-header h4">
      Question
    </div>
    <div class="card-block">
      <%= @answer.question.content %>
    </div>
</div>

<h1>Edit Answer</h1>

<%= render 'form', answer: @answer %>
<br >
<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<% @answers.each do |answer| %>
  <div class="card w-75 mx-auto my-3">
    <div class="card-header h4 bg-success">
      Answer
    </div>
    <div class="card-block">
      <%= answer.text %>
    </div>
    <div class="card-footer">
      <%= link_to 'Show', answer %>&nbsp;
      <% if answer.user == current_user %>
        <%= link_to 'Edit', edit_answer_path(answer) %>&nbsp;
        <%= link_to 'Delete', answer, method: :delete, data: { confirm: 'Are you sure?' } %>&nbsp;
      <% end %>
    </div>
  </div>
<% end %>


<br>

app/views/answers/new.html.erb
<div class="card w-75 mx-auto my-3">
    <div class="card-header h4">
      Question
    </div>
    <div class="card-block">
      <%= @question.content %>
    </div>
</div>

<div class="w-75 my-3 mx-auto">
    <h1>New Answer</h1>

    <%= render 'form', answer: @answer %>
    <br />
    <%= link_to 'Back', answers_path %>
</div>

app/views/answers/show.html.erb
<div class="card w-75 mx-auto my-3">
    <div class="card-header h4">
      Question
    </div>
    <div class="card-block">
      <%= @answer.question.content %>
    </div>
</div>

<div class="card w-50 mx-auto my-3">
    <div class="card-header h4 bg-success">
      Answer
    </div>
    <div class="card-block">
      <%= @answer.text %>
    </div>
    <div class="card-footer">
        <% if @answer.user == current_user %>
            <%= link_to 'Edit', edit_answer_path(@answer) %>&nbsp;
        <% end %>
        <%= link_to 'Back', answers_path %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Month Rails Project</title>
    <%= csrf_meta_tags %>


    <link rel="shortcut icon" href="/favicon.ico">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-light align-baseline">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'Quae', root_path, class:"navbar-brand mb-0"  %>
      <div class="collapse navbar-collapse container justify-content-between mt-1" id="navbarToggle">
        <ul class="nav navbar-nav">
          <li class='nav-item'> <%= link_to 'Home', root_path,   class:"nav-link"  %> </li>
          <li class='nav-item'> <%= link_to 'About', about_path,  class:"nav-link" %> </li>
          <li class='nav-item'> <%= link_to 'Contact', contact_path,  class:"nav-link" %> </li>
          <li class='nav-item'> <%= link_to 'Questions', :questions,  class:"nav-link" %> </li>
        </ul>
        <ul class='nav navbar-nav'>

          <% if user_signed_in? %>
            <li class='nav-item'><%= link_to 'My Profile', user_path(current_user.username), class:"nav-link" %></li>
            <li class='nav-item'> <%= link_to 'Log Out', signout_path, method: :delete, class:"nav-link" %> </li>

          <% else %>

            <li class='nav-item'> <%= link_to 'Sign Up', signup_path, class:"nav-link" %> </li>
            <li class='nav-item'> <%= link_to 'Sign In', signin_path, class:"nav-link btn btn-success" %></li>
        
          <% end %> 

        </ul>
      </div>
    </nav>
        <!-- Flash Messages -->
        <% flash.each do |name, message| %>
          <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
        <% end  %>
        <div class="container" id='main'>
            <%= yield %>
        </div> 
   <!-- Footer -->
    <footer class="small text-muted fixed-bottom">
      <div class="container">
        <hr>
        <center>
          <p>© <span id='year'></span> Nate Hare</p>
        </center>
      </div>
    </footer> 
    <script type="text/javascript">
      var currentYear = new Date().getFullYear();
      document.getElementById('year').innerText = currentYear;
    </script>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Quae–A Quora Clone</h1>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Post</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <% if !user_signed_in? %>
                <p>
                    <%= link_to 'Sign Up', signup_path, class:"btn btn-primary" %>
                </p>
            <% end %>
        </div>
        <div class="col-md-4">
            <h2>Answer</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <% if !user_signed_in? %>
                <p>
                    <%= link_to 'Sign Up', signup_path, class:"btn btn-primary" %>
                </p>
            <% end %>
        </div>
        <div class="col-md-4">
            <h2>Like</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <% if !user_signed_in? %>
                <p>
                    <%= link_to 'Sign Up', signup_path, class:"btn btn-primary" %>
                </p>
            <% end %>
        </div>
    </div>
</div>

app/views/pages/contact.html.erb
<div class="container">

    <h1>Contact Us</h1>

    <ul>
        <li>Github: <%= link_to 'n-hare', 'https://github.com/n-hare', target:'_blank' %></li>
        <li>Product Hunt: <%= link_to 'nate_hare', 'https://www.producthunt.com/@nate_hare', target:'_blank' %></li> 
        <li>Twitter: <%= link_to 'nate_hare', 'https://twitter.com/nate_hare', target:'_blank' %></li>
    </ul>

    <h2>About Me, Nate</h2>
    <ul>
        <li>Apple User</li>
        <li>From Ontario, Canada</li>
        <li>OneMonth Rails is my 4th Premium Course</li>
    </ul>

</div> <!-- div container end -->

app/views/pages/home.html.erb
<div class="jumbotron jumbotron-home text-center">
    <div class="container">
        <%= image_tag 'https://media.giphy.com/media/qF3loRbiqLT44/giphy.gif' %>
        <h1>Hello, Bonjour, Hola</h1>
        <p class='lead'>This app is a work in progress&#8230;</p>
    </div>
</div>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group w-75 my-3">
    <%= form.label :content, class:'invisible' %>
    <%= form.text_area :content, id: :question_content, class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>
<br >
<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<% @questions.each do |question| %>
  <div class="card w-75 mx-auto my-3">
    <div class="card-header h4">
      Question
    </div>
    <div class="card-block">
      <%= question.content %>
    </div>
    <div class="card-footer">
      <%= link_to 'Show', question %>&nbsp;
      <% if question.user == current_user %>
        <%= link_to 'Edit', edit_question_path(question) %>&nbsp;
        <%= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' } %>&nbsp;
      <% end %>
    </div>
  </div>
<% end %>


<br>
<% if user_signed_in? %>
  <%= link_to 'New Question', new_question_path, class: 'btn btn-primary mb-3 w-50 mx-auto text-center',style: 'display:block' %>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>
<br >
<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<div class="card w-75 mx-auto my-3">
    <div class="card-header h4">
      Question
    </div>
    <div class="card-block">
      <%= @question.content %>
      <br>
      <span class="text-muted small">—from <%= link_to @question.user.username, user_path(@question.user.username) %></span>
    </div>
    <div class="card-footer">
      <div class='content-flex'>
        <div>
          <% if @question.user == current_user %>
              <%= link_to 'Edit', edit_question_path(@question) %>&nbsp;
          <% end %>
          <%= link_to 'Back', questions_path %>
        </div>
        <div class='likes-info'>

          <%=  @question.votes_for.up.size%>&nbsp;
          <% if user_signed_in? %>
            <% if current_user.voted_up_on? @question %>
              <%= link_to '★', unlike_question_path(@question), method: :delete, class: 'unlike-star' %>
            <% else %>
               <%= link_to "☆", like_question_path(@question), method: :post, class: 'like-star'%>
            <% end %>
          <% else %>
            <span class='text-primary'>★</span>
          <% end %>
        </div>
      </div>
    </div>
</div>
<% @question.answers.order(:cached_votes_up => :desc).each do |answer| %>

  <div class="card w-50 mx-auto my-3">
    <div class="card-header h4 bg-success">
      Answer
    </div>
    <div class='card-block'> 
      <%= answer.text %>
      <br>
      <span class="text-muted small">—from <%= link_to answer.user.username, user_path(answer.user.username) %></span>
    </div>
    <div class="card-footer">
      <div class="content-flex">
        <div>
          <% if answer.user == current_user %>
            <%= link_to 'Edit', edit_answer_path(answer) %>&nbsp; 
            <%= link_to 'Delete', answer, method: :delete, data: { confirm: 'Are you sure?' } %> 
          <% end %>
        </div>
        <div class="like-info">
          <%=  answer.votes_for.up.size %>
          <% if user_signed_in? %>

            <% if current_user.voted_up_on? answer %>
              <%= link_to "➜", unvote_answer_path(answer), method: :delete, class: 'arrow arrow-unvote'%>
            <% else %>
              <%= link_to "⇨", vote_answer_path(answer), method: :post, class: 'arrow arrow-vote'%>
            <% end %>
          <% else %>
            <span class='text-primary arrow'>➜</span>
          <% end %>
        </div>
      </div>
    </div>
  </div> 
<% end %>

<% if @question.answers.empty? %>
        <p class='text-muted text-center'>Nothing here yet, be the first to answer?</p>
<% end %>
<br>
<% if user_signed_in? %>
  <%= link_to 'New Answer', new_answer_path, class: 'btn btn-primary mb-3 w-50 mx-auto text-center',style: 'display:block' %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p class="h4 mt-5">My Questions</p>
<% @user.questions.each do |question| %>
  <div class="card w-75 mx-auto my-3">
    <div class="card-header h4">
      Question
    </div>
    <div class="card-block">
      <%= question.content %>
    </div>
    <div class="card-footer">
      <%= link_to 'Show', question %>&nbsp;
      <% if question.user == current_user %>
        <%= link_to 'Edit', edit_question_path(question) %>&nbsp;
        <%= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' } %>&nbsp;
      <% end %>
    </div>
  </div>
<% end %>

<% if @user.questions.empty? %>
        <p class='text-muted text-center'>Nothing here, no questions yet</p>
<% end %>



<p class="h4 mt-5">Liked Questions</p>
<% @liked_questions.each do |liked_item| %>
  <div class="card w-75 mx-auto my-3">
    <div class="card-header h4">
      Question
    </div>
    <div class="card-block">
      <%= liked_item.content %>
    </div>
    <div class="card-footer">
      <%= link_to 'Show', liked_item %>
    </div>
  </div>
<% end %>

<% if @user.find_liked_items.empty? %>
        <p class='text-muted text-center'>Nothing here, no likes yet</p>
<% end %>


<p class="h4 mt-5">My Answers</p>
<% @user.answers.each do |answer| %>

  <div class="card w-50 mx-auto my-3">
    <div class="card-header h4 bg-success">
      Answer
    </div>
    <div class='card-block'> 
      <%= answer.text %>
    </div>
    <div class="card-footer">
        <%= link_to 'Show', answer.question %>&nbsp;
      <% if answer.user == current_user %>
        <%= link_to 'Edit', edit_answer_path(answer) %>&nbsp; 
        <%= link_to 'Delete', answer, method: :delete, data: { confirm: 'Are you sure?' } %> 
      <% end %>
    </div>
  </div> 

<% end %>
<% if @user.answers.empty? %>
        <p class='text-muted text-center'>Nothing here, no answers yet</p>
<% end %>